from __future__ import annotations

from pathlib import Path

try:
    from mcp.server import MCPServer
except ImportError as exc:  # pragma: no cover - exercised only without the optional runtime
    raise SystemExit("Canon requires the MCP Python SDK. Install it with: python3 -m pip install 'mcp>=2,<3'") from exc

try:
    from .canon_core import (
        explain_knowledge as explain,
        find_project_root,
        get_context as context,
        propose_knowledge as propose,
        rebuild_index,
        search_knowledge as search,
    )
except ImportError:
    from canon_core import (  # type: ignore
        explain_knowledge as explain,
        find_project_root,
        get_context as context,
        propose_knowledge as propose,
        rebuild_index,
        search_knowledge as search,
    )


mcp = MCPServer("Canon")


def _root(project_root: str | None) -> Path:
    return find_project_root(project_root)


@mcp.tool()
def get_context(task: str, scope: str = "global", project_root: str | None = None, limit: int = 12) -> str:
    """Return the project's established decisions, constraints, and preferences for a task.

    Call this before choosing a platform, provider, runtime, database, or library, and
    before writing a plan, config, or design doc - the answer is authority the project has
    already settled, and reading `knowledge/` by hand misses it. Scope is hierarchical
    (`client/acme/project/payments` inherits from `client/acme`), and this resolves
    inheritance, excludes sibling scopes, drops superseded decisions, and marks items
    generated by AI as evidence rather than authority. Reading the Markdown directly gets
    none of that.
    """
    return context(_root(project_root), task, scope, limit)


@mcp.tool()
def search_knowledge(
    query: str,
    scope: str = "global",
    include_superseded: bool = False,
    project_root: str | None = None,
    limit: int = 20,
) -> list[dict]:
    """Search established project knowledge by keyword, hiding superseded items by default.

    Use when the relevant scope is unknown or a specific topic needs locating; prefer
    `get_context` when the task's scope is known.
    """
    return search(_root(project_root), query, scope, include_superseded=include_superseded, limit=limit)


@mcp.tool()
def explain_knowledge(identifier: str, project_root: str | None = None) -> dict:
    """Explain where an established item came from: source path, scope, type, supersession, and Git history.

    Use this to answer why the project does something a particular way, what decided it,
    when it changed, or what an earlier choice was replaced by. Provenance and supersession
    live in Canon's metadata and Git history, not in the Markdown body, so reading the file
    cannot answer these.
    """
    return explain(_root(project_root), identifier)


@mcp.tool()
def propose_knowledge(
    title: str,
    body: str,
    document_type: str = "decision",
    scope: str = "global",
    supersedes: list[str] | None = None,
    project_root: str | None = None,
) -> dict:
    """Record a durable decision as a proposal for human review under .canon/proposals/.

    Use this whenever a decision should outlive the session - the project's answer to
    "remember this for later". Never write the decision into `knowledge/` directly and
    never keep it in an ad-hoc notes file: `knowledge/` is human-owned authority, and a
    proposal is how AI-generated text reaches it without silently becoming authoritative.
    Pass `supersedes` with the IDs of any decisions this one replaces.
    """
    return propose(
        _root(project_root),
        title=title,
        body=body,
        document_type=document_type,
        scope=scope,
        supersedes=supersedes or (),
    )


@mcp.tool()
def rebuild_knowledge_index(project_root: str | None = None) -> dict:
    """Rebuild the disposable local SQLite FTS index from human-owned Markdown."""
    return rebuild_index(_root(project_root))


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
